name: RO-Crate to Pages
on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: RO-Crate to Pages
          uses: vliz-be-opsci/rocrate-to-pages@latest
          with:
            multiple_rocrates: true
            RELEASE_managment: true
            RELEASE_versioning: tag
            INCLUDE_draft: true
            draft_folder_name: latest
            index_html: true
        # Deploy to GH-Pages branch
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./unicornpages
